### ISSUE TITLE
Contact Icons are not accessible

### ISSUE THREAD

**Issue by aburdiss** [webdevtrev/brookville-xc#4]
There is no hidden text or aria labels on the icons in the header. Adding text that is visually hidden for accessibility may be the best option. This may be a useful class to add to your global css file to reference anywhere on the site:
```css
.visually-hidden-accessibility {
    -webkit-clip-path: inset(100%);
    clip-path: inset(100%);
    clip: rect(1px,1px,1px,1px);
    height: 1px;
    overflow: hidden;
    position: absolute;
    white-space: nowrap;
    width: 1px;
}
```
